# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: federated.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='federated.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x66\x65\x64\x65rated.proto\"\xb7\x01\n\x10\x46\x65\x64\x65ratedRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\r\n\x05round\x18\x02 \x01(\t\x12\x14\n\x0cserver_state\x18\x03 \x01(\x0c\x12\x1a\n\x12sampled_train_data\x18\x04 \x01(\x0c\x12\x1c\n\x14\x63lients_participated\x18\x05 \x01(\t\x12\x18\n\x10\x62roadcasted_bits\x18\x06 \x01(\t\x12\x17\n\x0f\x61ggregated_bits\x18\x07 \x01(\t\"%\n\x11\x46\x65\x64\x65ratedResponse\x12\x10\n\x08response\x18\x01 \x01(\t2C\n\x10\x46\x65\x64\x65ratedService\x12/\n\x06Search\x12\x11.FederatedRequest\x1a\x12.FederatedResponseb\x06proto3'
)




_FEDERATEDREQUEST = _descriptor.Descriptor(
  name='FederatedRequest',
  full_name='FederatedRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='FederatedRequest.timestamp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='round', full_name='FederatedRequest.round', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='server_state', full_name='FederatedRequest.server_state', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sampled_train_data', full_name='FederatedRequest.sampled_train_data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clients_participated', full_name='FederatedRequest.clients_participated', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='broadcasted_bits', full_name='FederatedRequest.broadcasted_bits', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='aggregated_bits', full_name='FederatedRequest.aggregated_bits', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=203,
)


_FEDERATEDRESPONSE = _descriptor.Descriptor(
  name='FederatedResponse',
  full_name='FederatedResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='FederatedResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=242,
)

DESCRIPTOR.message_types_by_name['FederatedRequest'] = _FEDERATEDREQUEST
DESCRIPTOR.message_types_by_name['FederatedResponse'] = _FEDERATEDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FederatedRequest = _reflection.GeneratedProtocolMessageType('FederatedRequest', (_message.Message,), {
  'DESCRIPTOR' : _FEDERATEDREQUEST,
  '__module__' : 'federated_pb2'
  # @@protoc_insertion_point(class_scope:FederatedRequest)
  })
_sym_db.RegisterMessage(FederatedRequest)

FederatedResponse = _reflection.GeneratedProtocolMessageType('FederatedResponse', (_message.Message,), {
  'DESCRIPTOR' : _FEDERATEDRESPONSE,
  '__module__' : 'federated_pb2'
  # @@protoc_insertion_point(class_scope:FederatedResponse)
  })
_sym_db.RegisterMessage(FederatedResponse)



_FEDERATEDSERVICE = _descriptor.ServiceDescriptor(
  name='FederatedService',
  full_name='FederatedService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=244,
  serialized_end=311,
  methods=[
  _descriptor.MethodDescriptor(
    name='Search',
    full_name='FederatedService.Search',
    index=0,
    containing_service=None,
    input_type=_FEDERATEDREQUEST,
    output_type=_FEDERATEDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FEDERATEDSERVICE)

DESCRIPTOR.services_by_name['FederatedService'] = _FEDERATEDSERVICE

# @@protoc_insertion_point(module_scope)
